appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: E6V3BKh8nmEoKZbGwgCLlHkYvIGSOrGcMZZlbeBv5B1nYgDCDAD5bJgiLXxWuzYS3Jv4zd+VMGZmfsoMav05FP7jUkzis4AlUwH4QBMjWwnIc8npxUx4qucxlBWRMj91TyB54j6zJBhmxJk52MkshHk/ckdg39dyTVO7iEnLD8RWk7gOOFcZdnSVdPTnZs/U6UvCAYPM8yCCAxVCD3xoPus5f6nw0rxE5+Gfssbrlfzfq2Ei1NDA4qxfAUnHNLlw+zCjOD3juLy8T98xI2Iv0gv3WTNKa88NqM0MYYnDOBWj7q70ot+m6fqFBi56iKO+jcdzVQbocwOdR1LS7YShQqfkFrlXvyfvMDEvM26edSNUygvM2Voe4FiENVoXq5+dggR4bVGo7RLiNkWLkfAvDTyV6nQZkWwTJDkM4+6Kx+0HI6v4ot3vghEbBfM8YLwk2nr2Aewo/m9juhTErpt2lWWIStm53SCcD7uAfl3SRxJCusmNpqh0cFG2ItXeDeqfnTnndUFo6Uiu3rZbXKDWcPWHxQd0GQl64+xQy+B/frr5lzNSmBbMR+ByihlYQX+JzlLIUPGs9NfsNm961sOdTSfxIfMQ8aB0YJdT1osftJ4YhyyGnkSZ3MxiIT0soq4beKxFASk8FIXHLAqwlbBTGZox2tSPC/WCvcFd64UB798=}
